---
db:
  db_name: 'stocks_data'
  app_url: 'http://0.0.0.0'
  app_ip: '0.0.0.0'
  app_port: '8888'

stocks:
  index_list: ['CSCO', 'C', 'INTL', 'AIG', 'IBM', 'SPY']

system:
  collection_period: 300
  log_path: 'main.log'
